name: Extra 07 - Simulated Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Entorno de despliegue'
        required: true
        type: choice
        options:
          - develop
          - test
          - production

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:
      - name: Simular build
        run: echo "Build completado"

      - name: Simular deploy
        run: echo "Deploy realizado en ${{ inputs.environment }}"
